In [10]:
import pandas as pd

In [7]:
import json

# Definition of the extraction data

# To extract car overview
def car_overview_dict_creator(overview):
    overview_dict = json.loads(overview.replace("'", '"').replace('None', "1"))
    all_overviews = {}
    for dictionary in overview_dict['top']:
        all_overviews.update({dictionary['key']: dictionary['value']})
    return all_overviews  # Return corrected variable name 'all_overviews'

# To extract car feature
def car_feature_dict_creator(feature):
    all_features = {}
    feature_dict = json.loads(feature.replace("'", '"').replace('None', "1"))
    for dictionary in feature_dict['top']:
        all_features.update({dictionary['value']: True})
        for section in feature_dict.get('data', []):
            for item in section.get('list', []):
                all_features.update({item['value']: True})
    return all_features

# To extract car specs
def car_spec_dict_creator(spec):
    all_specs = {}
    specs_dict = json.loads(spec.replace("'", '"').replace('None', "null"))
    for dictionary in specs_dict.get('top', []):
        all_specs.update({dictionary['key']: dictionary['value']})
    # Extract nested specifications
    for dictionary in specs_dict.get('data', []):
        for item in dictionary.get('list', []):
            all_specs.update({item['key']: item['value']})
    return all_specs

In [8]:
import pandas as pd
import json

# Load data from Excel
df = pd.read_excel(r"C:\Users\plangote\OneDrive - DXC Production\Desktop\Car Dheko - Used Car Price Prediction\bangalore_cars.xlsx")

# Extract car detail
def extract_car_detail(detail):
    return json.loads(detail.replace("'", '"').replace('None', "1"))

df['new_car_detail'] = df['new_car_detail'].apply(extract_car_detail)
df_car_detail = pd.DataFrame(df['new_car_detail'].tolist())

# Extract car overview
df['new_car_overview'] = df['new_car_overview'].apply(lambda overview: car_overview_dict_creator(overview))
df_car_overview = pd.DataFrame(df['new_car_overview'].tolist())

# Extract car features
df['new_car_feature'] = df['new_car_feature'].apply(lambda feature: car_feature_dict_creator(feature))
feature_df = pd.json_normalize(df['new_car_feature']).fillna(0).astype(int)

# Extract car specs
df['new_car_specs'] = df['new_car_specs'].apply(lambda spec: car_spec_dict_creator(spec))
df_car_specs = pd.DataFrame(df['new_car_specs'].tolist())

# Combine all dataframes
df_combined = pd.concat([df_car_detail, df_car_overview, feature_df, df_car_specs], axis=1)

# Add city column and save to CSV
df_combined['city'] = 'Bangalore'
df_combined.to_csv('Bangalore_cars.csv', index=False)

In [9]:
df = pd.read_csv("Bangalore_cars.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,city
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,Drum,176 Kmph,9.6 Seconds,"Tubeless,Radial",5.0,296-litres,17,17,NaN,Bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,Drum,177 kmph,12.1 seconds,"Tubeless, Radial",4.0,505 litres,16,16,NaN,Bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,Drum,164 Kmph,14.5 Seconds,"Tubeless,Radial",5.0,175-litres,NaN,NaN,NaN,Bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,Drum,180 Kmph,11.9 Seconds,Tubeless,5.0,295-litres,16,16,NaN,Bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,Drum,165 Kmph,12.9 Seconds,Tubeless,5.0,256-liters,14,14,NaN,Bangalore

In [10]:
import pandas as pd
import json

# Load data from Excel
df = pd.read_excel(r"C:\Users\plangote\OneDrive - DXC Production\Desktop\Car Dheko - Used Car Price Prediction\chennai_cars.xlsx")

# Extract car detail
def extract_car_detail(detail):
    return json.loads(detail.replace("'", '"').replace('None', "1"))

df['new_car_detail'] = df['new_car_detail'].apply(extract_car_detail)
df_car_detail = pd.DataFrame(df['new_car_detail'].tolist())

# Extract car overview
df['new_car_overview'] = df['new_car_overview'].apply(lambda overview: car_overview_dict_creator(overview))
df_car_overview = pd.DataFrame(df['new_car_overview'].tolist())

# Extract car features
df['new_car_feature'] = df['new_car_feature'].apply(lambda feature: car_feature_dict_creator(feature))
feature_df = pd.json_normalize(df['new_car_feature']).fillna(0).astype(int)

# Extract car specs
df['new_car_specs'] = df['new_car_specs'].apply(lambda spec: car_spec_dict_creator(spec))
df_car_specs = pd.DataFrame(df['new_car_specs'].tolist())

# Combine all dataframes
df_combined = pd.concat([df_car_detail, df_car_overview, feature_df, df_car_specs], axis=1)

# Add city column and save to CSV
df_combined['city'] = 'chennai'
df_combined.to_csv('chennai_cars.csv', index=False)

In [11]:
df = pd.read_csv("chennai_cars.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Super Charger,Front Tread,Rear Tread,Gross Weight,Turning Radius,Top Speed,Acceleration,BoreX Stroke,Ground Clearance Unladen,city
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,No,1280mm,1290mm,1540kg,4.5 metres,145 Kmph,15.7 Seconds,NaN,NaN,chennai
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,No,NaN,NaN,NaN,5.0,NaN,11.7,72.2 x 81.3,NaN,chennai
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,No,1400mm,1385mm,NaN,4.7 metres,165 Kmph,14.3 Seconds,NaN,NaN,chennai
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,No,NaN,NaN,NaN,5.1 meters,172 Kmph,13.7 Seconds,NaN,NaN,chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,...,No,1530mm,1530mm,1315kg,4.8 Meters,NaN,NaN,NaN,NaN,chennai
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,...,No,1560mm,1567mm,1777kg,5.2 metres,156 Kmph,13.9 Seconds,NaN,NaN,chennai
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,...,No,1540 mm,1530 mm,NaN,5.1m,154.19 kmph,NaN,77x85.8,209 mm,chennai
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,...,No,1578mm,1568mm,2250kg,5.75meters,NaN,NaN,74.5 x 81 mm,NaN,chennai
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,...,No,1541 mm,1581 mm,NaN,5.5 metres,226 Kmph,7.7 Seconds,NaN,NaN,chennai

In [12]:
import pandas as pd
import json

# Load data from Excel
df = pd.read_excel(r"C:\Users\plangote\OneDrive - DXC Production\Desktop\Car Dheko - Used Car Price Prediction\delhi_cars.xlsx")

# Extract car detail
def extract_car_detail(detail):
    return json.loads(detail.replace("'", '"').replace('None', "1"))

df['new_car_detail'] = df['new_car_detail'].apply(extract_car_detail)
df_car_detail = pd.DataFrame(df['new_car_detail'].tolist())

# Extract car overview
df['new_car_overview'] = df['new_car_overview'].apply(lambda overview: car_overview_dict_creator(overview))
df_car_overview = pd.DataFrame(df['new_car_overview'].tolist())

# Extract car features
df['new_car_feature'] = df['new_car_feature'].apply(lambda feature: car_feature_dict_creator(feature))
feature_df = pd.json_normalize(df['new_car_feature']).fillna(0).astype(int)

# Extract car specs
df['new_car_specs'] = df['new_car_specs'].apply(lambda spec: car_spec_dict_creator(spec))
df_car_specs = pd.DataFrame(df['new_car_specs'].tolist())

# Combine all dataframes
df_combined = pd.concat([df_car_detail, df_car_overview, feature_df, df_car_specs], axis=1)

# Add city column and save to CSV
df_combined['city'] = 'delhi'
df_combined.to_csv('delhi_cars.csv', index=False)

In [13]:
df = pd.read_csv("delhi_cars.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Top Speed,Acceleration,Gross Weight,Front Tread,Rear Tread,BoreX Stroke,Compression Ratio,Ground Clearance Unladen,city
0,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,delhi
1,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,2016,...,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,delhi
2,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,2020,...,NaN,217 Kmph,NaN,2360kg,NaN,NaN,NaN,NaN,NaN,delhi
3,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,2018,...,4.8,NaN,NaN,1335,1530,1530,NaN,NaN,NaN,delhi
4,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2017,...,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN,delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1480,0,Petrol,Sedan,"60,000",Automatic,1,1st Owner,Honda,Honda City,2019,...,5.3 metres,195 Kmph,10 Seconds,1455kg,1490mm,1480mm,73.0 X 89.4 mm,10.3:1,NaN,delhi
1481,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Kia,Kia Sonet,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,delhi
1482,0,Petrol,Sedan,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Verna,2011,...,5.2 metres,196km/hr,10.5 Seconds,NaN,NaN,NaN,77.0mm X 85.44mm,10.5;1,NaN,delhi
1483,0,Diesel,SUV,"38,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,2019,...,5.3 metres,160.58kmph,10.83 s,NaN,NaN,NaN,NaN,NaN,190mm,delhi
1484,0,Diesel,SUV,"7,000",Automatic,0,0th Owner,MG,MG Gloster,2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,delhi

In [14]:
import pandas as pd
import json

# Load data from Excel
df = pd.read_excel(r"C:\Users\plangote\OneDrive - DXC Production\Desktop\Car Dheko - Used Car Price Prediction\hyderabad_cars.xlsx")

# Extract car detail
def extract_car_detail(detail):
    return json.loads(detail.replace("'", '"').replace('None', "1"))

df['new_car_detail'] = df['new_car_detail'].apply(extract_car_detail)
df_car_detail = pd.DataFrame(df['new_car_detail'].tolist())

# Extract car overview
df['new_car_overview'] = df['new_car_overview'].apply(lambda overview: car_overview_dict_creator(overview))
df_car_overview = pd.DataFrame(df['new_car_overview'].tolist())

# Extract car features
df['new_car_feature'] = df['new_car_feature'].apply(lambda feature: car_feature_dict_creator(feature))
feature_df = pd.json_normalize(df['new_car_feature']).fillna(0).astype(int)

# Extract car specs
df['new_car_specs'] = df['new_car_specs'].apply(lambda spec: car_spec_dict_creator(spec))
df_car_specs = pd.DataFrame(df['new_car_specs'].tolist())

# Combine all dataframes
df_combined = pd.concat([df_car_detail, df_car_overview, feature_df, df_car_specs], axis=1)

# Add city column and save to CSV
df_combined['city'] = 'hyderabad'
df_combined.to_csv('hyderabad_cars.csv', index=False)

In [15]:
df = pd.read_csv("hyderabad_cars.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Front Brake Type,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Top Speed,Acceleration,Ground Clearance Unladen,city
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,Disc,Drum,"Tubeless,Radial",R16,5,280,NaN,NaN,NaN,hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,Disc,Drum,Tubeless,NaN,5,215-litres,135 Kmph,19 Seconds,NaN,hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,Disc,Drum,"Tubeless, Radial",NaN,5,NaN,NaN,NaN,NaN,hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,Disc,Drum,"Tubeless,Radial",16,5,339-litres,180 Kmph,12.36 seconds,NaN,hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,Disc,Drum,"Radial, Tubeless",18,3,NaN,NaN,NaN,NaN,hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,Disc & Caliper Type,Disc & Caliper Type,"Tubeless,Radial",17,5,NaN,175 kmph,12.5 Seconds,NaN,hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,Disc,Disc,"Tubeless,Radial",20,4,540-litres,250 Kmph,6.4 Seconds,NaN,hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,Ventilated Disc,Ventilated Disc,"Tubeless, Runflat",R18,4,520-litres,235kmph,7.5,NaN,hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,Disc,Drum,Tubeless Radial Tyres,NaN,5,350,154.19 kmph,13.25 Seconds,209 mm,hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,Ventilated Disc,Drum,"Tubeless,Radial",15,5,300-litres,155 Kmph,13.3 Seconds,NaN,hyderabad

In [16]:
import pandas as pd
import json

# Load data from Excel
df = pd.read_excel(r"C:\Users\plangote\OneDrive - DXC Production\Desktop\Car Dheko - Used Car Price Prediction\jaipur_cars.xlsx")

# Extract car detail
def extract_car_detail(detail):
    return json.loads(detail.replace("'", '"').replace('None', "1"))

df['new_car_detail'] = df['new_car_detail'].apply(extract_car_detail)
df_car_detail = pd.DataFrame(df['new_car_detail'].tolist())

# Extract car overview
df['new_car_overview'] = df['new_car_overview'].apply(lambda overview: car_overview_dict_creator(overview))
df_car_overview = pd.DataFrame(df['new_car_overview'].tolist())

# Extract car features
df['new_car_feature'] = df['new_car_feature'].apply(lambda feature: car_feature_dict_creator(feature))
feature_df = pd.json_normalize(df['new_car_feature']).fillna(0).astype(int)

# Extract car specs
df['new_car_specs'] = df['new_car_specs'].apply(lambda spec: car_spec_dict_creator(spec))
df_car_specs = pd.DataFrame(df['new_car_specs'].tolist())

# Combine all dataframes
df_combined = pd.concat([df_car_detail, df_car_overview, feature_df, df_car_specs], axis=1)

# Add city column and save to CSV
df_combined['city'] = 'jaipur'
df_combined.to_csv('jaipur_cars.csv', index=False)

In [17]:
df = pd.read_csv("jaipur_cars.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Acceleration,Tyre Type,Alloy Wheel Size,No Door Numbers,Cargo Volumn,Gross Weight,BoreX Stroke,Compression Ratio,Ground Clearance Unladen,city
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,11.9 Seconds,Tubeless,16,5.0,295-litres,NaN,NaN,NaN,NaN,jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,NaN,"Radial, Tubeless",NaN,5.0,268,1335,NaN,NaN,NaN,jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,15.05 Seconds,"Tubeless, Radial",NaN,5.0,235-litres,1250kg,73 X 82 mm,11.0:1,NaN,jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,12.9 Seconds,Tubeless,NaN,5.0,256,NaN,NaN,NaN,NaN,jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,18.6 Seconds,Tubeless Tyres,NaN,5.0,180-liters,1350kg,69 x 72 mm,NaN,NaN,jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,NaN,"Tubeless,Radial",14,5.0,170-litres,NaN,NaN,NaN,NaN,jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,17.7 seconds,"Tubeless,Radial",12,5.0,NaN,1140kg,68.5 x 72.0 mm,NaN,NaN,jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,"Tubeless, Radial",16,5.0,405,NaN,NaN,NaN,NaN,jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,17.7 seconds,"Tubeless,Radial",12,5.0,NaN,1140kg,68.5 x 72.0 mm,NaN,NaN,jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,12.36 seconds,"Tubeless,Radial",NaN,5.0,339-litres,1340kg,NaN,NaN,NaN,jaipur

In [18]:
import pandas as pd
import json

# Load data from Excel
df = pd.read_excel(r"C:\Users\plangote\OneDrive - DXC Production\Desktop\Car Dheko - Used Car Price Prediction\kolkata_cars.xlsx")

# Extract car detail
def extract_car_detail(detail):
    return json.loads(detail.replace("'", '"').replace('None', "1"))

df['new_car_detail'] = df['new_car_detail'].apply(extract_car_detail)
df_car_detail = pd.DataFrame(df['new_car_detail'].tolist())

# Extract car overview
df['new_car_overview'] = df['new_car_overview'].apply(lambda overview: car_overview_dict_creator(overview))
df_car_overview = pd.DataFrame(df['new_car_overview'].tolist())

# Extract car features
df['new_car_feature'] = df['new_car_feature'].apply(lambda feature: car_feature_dict_creator(feature))
feature_df = pd.json_normalize(df['new_car_feature']).fillna(0).astype(int)

# Extract car specs
df['new_car_specs'] = df['new_car_specs'].apply(lambda spec: car_spec_dict_creator(spec))
df_car_specs = pd.DataFrame(df['new_car_specs'].tolist())

# Combine all dataframes
df_combined = pd.concat([df_car_detail, df_car_overview, feature_df, df_car_specs], axis=1)

# Add city column and save to CSV
df_combined['city'] = 'kolkata'
df_combined.to_csv('kolkata_cars.csv', index=False)

In [19]:
df = pd.read_csv("kolkata_cars.csv")
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Tyre Type,Alloy Wheel Size,No Door Numbers,Ground Clearance Unladen,Cargo Volumn,Compression Ratio,Acceleration,Top Speed,city
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,Solid Disc,"Tubeless,Radial",17,4.0,NaN,NaN,NaN,NaN,NaN,kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,Drum,NaN,NaN,5.0,185mm,222,NaN,NaN,NaN,kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,Drum,"Tubeless, Radial",NaN,5.0,NaN,405,NaN,NaN,NaN,kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,Drum,"Tubeless,Radial",14,5.0,NaN,295 Lit,:1,12.96 Sec,NaN,kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,Drum,"Tubeless,Radial",16,5.0,NaN,460-litres,NaN,8.2 Seconds,212 Kmph,kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Drum,"Tubeless, Radial",NaN,5.0,NaN,313,NaN,NaN,NaN,kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Drum,Tubeless Tyres,NaN,5.0,NaN,177-litres,NaN,19 Seconds,140 kmph,kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Solid Disc,"Tubeless,Radial",17,4.0,NaN,475-litres,9.3:1,8.8 Seconds,230km/hr,kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Drum,"Tubeless,Radial",14,5.0,NaN,236-liters,NaN,15 Seconds,156 Kmph,kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Drum,"Tubeless,Radial",16,5.0,NaN,410-litres,NaN,14.20 Seconds,168 Kmph,kolkata

In [20]:
import pandas as pd
from pathlib import Path

# List of CSV file names
csv_files = [
    'Bangalore_cars.csv', 'chennai_cars.csv', 'delhi_cars.csv',
    'hyderabad_cars.csv', 'jaipur_cars.csv', 'kolkata_cars.csv'
]

# Create a list of dataframes from CSV files
dataframes = [pd.read_csv(Path(file)) for file in csv_files]

# Concatenate all dataframes into one
concatenated_df = pd.concat(dataframes, ignore_index=True)

# Save the concatenated dataframe to a new CSV file
car_details_path = Path("car_details.csv")
concatenated_df.to_csv(car_details_path, index=False)

print(f"Concatenated CSV saved as {car_details_path.name}")

Concatenated CSV saved as car_details.csv

In [21]:
df = pd.read_csv("car_details.csv")
df

C:\Users\plangote\AppData\Local\Temp\ipykernel_9340\965388365.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("car_details.csv")

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,city
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Drum,NaN,NaN,"Tubeless, Radial",5.0,313,NaN,NaN,NaN,kolkata
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Drum,140 kmph,19 Seconds,Tubeless Tyres,5.0,177-litres,NaN,NaN,NaN,kolkata
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Solid Disc,230km/hr,8.8 Seconds,"Tubeless,Radial",4.0,475-litres,17,17,NaN,kolkata
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,14,14,NaN,kolkata
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5.0,410-litres,16,16,NaN,kolkata